npm install requests
npm install fs
npm install os
npm install child_process
npm install readline-sync
pip3 install pyarmor
pip3 install shutil.py
pip3 install pyautogui
pip3 install ctypes
pip3 install uuid
pip3 install platform
pip3 install os
pip3 install requests
pip3 install dhooks
pip3 install ctypes
pip3 install re
pip3 install sys
pip3 install loads
pip3 install subprocess
pip3 install base64
pip3 install random
pip3 install string
pip3 install datetime
pip3 install sqlite3
pip3 install browserhistory
pip3 install pycryptodome>=3.6.6
